fix indentation in ci-gate block

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -69,11 +69,11 @@ jobs:
         run: | 
           docker compose --env-file .env.e2e down -v  
 
-    ci-gate:
-      - name: Verify CI Quality Checks(lint, build, unit test, server e2e tests)
-        run: |
-          if [[ "${{ needs.build_and_test.result }}" != "success" ]]; then
-            echo "Required jobs failed!"
-            exit 1
-          fi       
+  ci-gate:
+    - name: Verify CI Quality Checks(lint, build, unit test, server e2e tests)
+      run: |
+        if [[ "${{ needs.build_and_test.result }}" != "success" ]]; then
+          echo "Required jobs failed!"
+          exit 1
+        fi       
           
