make security scan gate

diff --git a/.github/workflows/security-scan.yml b/.github/workflows/security-scan.yml
--- a/.github/workflows/security-scan.yml
+++ b/.github/workflows/security-scan.yml
@@ -54,7 +54,7 @@ jobs:
       - name: Run Semgrep Scan
         run: semgrep scan --config auto --error
 
-  secret-scan:
+  secretscan:
     name: Secret & Dotenv Leak Scan
     runs-on: ubuntu-latest
     steps:
@@ -62,5 +62,17 @@ jobs:
       uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
       with:
         fetch-depth: 0 # Deep history check
+
+  security-scan-gate:
+    runs-on: ubuntu-latest
+    needs: [codeql,semgrep,secret-scan]
+    if: always()
+    steps:
+      - name: Verify all security scans have succeeded
+        run: |
+          if [[ "${{ needs.codeql.result }}" != "success" || "${{ needs.semgrep.result }}" != "success" || "${{ needs.secretscan.result }}" != "success" ]]; then
+            echo "Required jobs failed!"
+            exit 1
+          fi
 
     # TODO dependabot
